org.gradle.jvmargs=-Xmx2048M
org.gradle.parallel=true

minecraft_version=1.19.4
enabled_platforms=forge

# Moved to modprops.gradle
#archives_base_name=
#mod_version=
#maven_group=

# CosmicDan: All these are latest for 1.19.4, as of 2025.01.15
# From https://www.curseforge.com/minecraft/mc-mods/architectury-api/files?version=1.19.4
architectury_version=8.2.91
# From https://fabricmc.net/develop/
fabric_loader_version=0.16.9
# From https://www.curseforge.com/minecraft/mc-mods/fabric-api/files?version=1.19.4
fabric_api_version=0.87.2+1.19.4
# RECOMMENDED version, from https://files.minecraftforge.net/net/minecraftforge/forge/index_1.19.4.html
forge_version=1.19.4-45.3.0
