modLoader = "javafml"
loaderVersion = "[45,)"
#issueTrackerURL = ""
license = "LGPL3"

[[mods]]
modId = "sleepingoverhaul"
version = "${version}"
displayName = "Sleeping Overhaul"
authors = "CosmicDan"
description = '''
Replaces skip-to-day on sleep with a beautiful panoramic timelapse, and more!
'''
logoFile = "logo.png"
displayURL = "https://github.com/CosmicDan-Minecraft/SleepingOverhaul2/"

[[dependencies.sleepingoverhaul]]
modId = "forge"
mandatory = true
versionRange = "[45,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.sleepingoverhaul]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.sleepingoverhaul]]
modId = "architectury"
mandatory = true
versionRange = "[8.2.91,)"
ordering = "AFTER"
side = "BOTH"
