modLoader = "javafml"
loaderVersion = "[40,)"
#issueTrackerURL = ""
license = "LGPL3"

[[mods]]
modId = "sleepingoverhaul"
version = "${version}"
displayName = "Sleeping Overhaul 2"
authors = "CosmicDan"
description = '''
Replaces skip-to-day on sleep with a beautiful panoramic timelapse, and more!
'''
logoFile = "logo.png"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/sleepingoverhaul2"

[[dependencies.sleepingoverhaul]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.sleepingoverhaul]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.sleepingoverhaul]]
modId = "architectury"
mandatory = true
versionRange = "[4.12.94,)"
ordering = "AFTER"
side = "BOTH"
